### ISSUE TITLE
Error when fetching from localhost, but fine from 127.0.01

### ISSUE THREAD

**Issue by lloydtao** [johannschopplich/nuxt-api-party#8]
## Issue

`nuxt-api-party` is unable to fetch from `localhost`, but substituting it with `127.0.0.1` with the exact same setup works perfectly.

The API response is identical for both `localhost` and `127.0.0.1` when tested manually. Additionally, the backend logs do not show any footprints at all when `localhost` is used, so I believe that this is an issue with `nuxt-api-party`.

### Config

```ts
  apiParty: {
    endpoints: {
      backend: {
        url: "http://localhost:8000",
      },
    },
  },
```

### Execution

```ts
const data = await $backend("/api/users/lloydtao/?format=json");
```

### Error

```
[nitro] [dev] [unhandledRejecto 
n] FetchError: 500 Failed to fetch from API endpoint "backend" (/api/__api_party/backend)       
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetcher (S:\Users\Lewis\Documents\GitHub\gridlink\frontends\web\node_modules\nuxt-api-party\dist\runtime\composables\$api.mjs:22:31)
    at async Proxy.fetchUser (S:\Users\Lewis\Documents\GitHub\gridlink\frontends\web\stores\user.ts:20:20)
```

### API

Returning as expected when called manually:

![image](https://user-images.githubusercontent.com/41923457/210391195-b26645ec-88df-4a8a-a369-26707c0cf967.png)

### Config

```ts
  apiParty: {
    endpoints: {
      backend: {
        url: "http://127.0.0.1:8000",
      },
    },
  },
```

### Execution

```ts
const data = await $backend("/api/users/lloydtao/?format=json");
```

### Output

```
{
  "username": "lloydtao",       
  "profile": {
    "display_name": "leighton",
...
```

### API

Returning as expected when called manually:

![image](https://user-images.githubusercontent.com/41923457/210391044-fa28e4cb-29db-4818-b290-4e5a30b56331.png)

**Comment by johannschopplich** [comment]
May I ask what the objective of your use-case is? The Nuxt module is intended for third-party APIs. Keep in mind, that every request to the Nuxt API Party server handler will result in another request to the actual API. It is intended to mask APIs with token requirements.

If you just want to connect a locally deployed server, maybe [`nuxt-proxy`](https://github.com/wobsoriano/nuxt-proxy) or the default `useFetch` would be more suitable?

**Comment by lloydtao** [comment]
> May I ask what the objective of your use-case is? The Nuxt module is intended for third-party APIs.

Certainly. I have a backend REST API which is fully decoupled from the frontend. It has its own domain, infrastructure and authentication via token, so is effectively third-party. The endpoint that I'm fetching in this example is unauthenticated.  

When developing, the backend and frontend run on localhost:8000 and :3000 respectively. 

I'm interested in this package mainly due to the features listed in the README. It seems like a good wrapper for avoiding code repetition and boilerplate.

**Comment by johannschopplich** [comment]
Actually, I'm not sure if I'm able to fix this issue. Under the hood, the Nuxt server route handles the fetch call to your API: https://github.com/johannschopplich/nuxt-api-party/blob/8978e57415927d25969cd316d4c33fb3c3c4c138/src/runtime/server.ts#L28

The `$fetch` internal method is auto-imported by Nuxt from [ofetch](https://github.com/unjs/ofetch). If it won't fetch data from `localhost`, I'm not sure what to do about it.

**Comment by lloydtao** [comment]
Super weird. Here's some more Nuxt 3 examples of `localhost` not working while `127.0.0.1` does:
- _"The problem was that fetch() didn't reconize localhost:9000 for some reason, but when I changed BASE_URL to 127.0.0.1:9000 it started to work."_ - https://stackoverflow.com/questions/73098374/nuxt-3-fetch-method-doesnt-work-with-golang-servers
- _"Had a similar issue. I got it to work by changing localhost -> 127.0.0.1."_ - https://www.reddit.com/r/Nuxt/comments/zqq0cg/nuxtjs_3_fetch_refuses_to_connect_to_local_server/

We may need to raise an issue higher up the chain.

**Comment by johannschopplich** [comment]
Excellent deep-dive. Thank you! 😃 Would you mind raising an issue for [Nuxt](https://github.com/nuxt/framework)? Let's keep this issue open until one of the main devs comment on the issue.

**Comment by lloydtao** [comment]
Raised: https://github.com/nuxt/framework/issues/10016 ✨

**Comment by johannschopplich** [comment]
Closing this issue, as pointed out in https://github.com/nuxt/nuxt/issues/12358#issuecomment-1397230556 that it is a Node "issue".
